services:
    db:
      image: postgres:13.4
      container_name: db
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=krypnite
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports: 
        - "5432:5432"
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment: 
        - WAIT_HOSTS=db
      container_name: web
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "5050:80"