# Generated by Django 3.2.12 on 2022-02-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0002_alter_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='secondary_address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='primary_address',
            field=models.CharField(max_length=200),
        ),
    ]
