# Generated by Django 3.2.12 on 2022-02-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_alter_billingprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='customer_payment_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
