# Generated by Django 3.2.10 on 2022-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sales_tax',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=100),
        ),
    ]
