# Generated by Django 3.2.10 on 2022-01-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_cart_sales_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sales_tax',
        ),
    ]
