# Generated by Django 3.2.9 on 2021-11-03 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krypniteweb', '0002_product_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+40123456789'. Up to 12 digits allowed.", regex='^\\+{1}40\\d{9}$')])),
                ('description', models.TextField(max_length=200)),
                ('estimation_time', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
