# Generated by Django 3.2.9 on 2021-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krypniteweb', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
