# Generated by Django 3.2.12 on 2022-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krypniteweb', '0011_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('cars', 'Cars'), ('cosmetics', 'Cosmetics')], default='cars', max_length=25, null=True),
        ),
    ]
