# Generated by Django 3.2.12 on 2022-02-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krypniteweb', '0012_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrivals',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cars', 'Cars'), ('cosmetics', 'Cosmetics'), ('outlet', 'Outlet'), ('jewerly', 'Jewerly'), ('accesories', 'Accesories'), ('toys', 'Toys'), ('books', 'Books'), ('gaming', 'Gaming')], default='cars', max_length=25),
        ),
    ]
