# Generated by Django 3.2.10 on 2022-01-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_app', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('created', 'Created'), ('payed', 'Payed'), ('shipping_in_progress', 'Shipping in progress'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('returned', 'Returned')], default='created', max_length=100)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=1.99, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_app.cart')),
            ],
        ),
    ]
