# Generated by Django 3.2.10 on 2022-01-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cart_subtotal'),
        ('order_checkout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercheckout',
            unique_together={('order_id', 'cart')},
        ),
    ]
