# Generated by Django 3.2.10 on 2022-01-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_checkout_app', '0002_alter_ordercheckout_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercheckout',
            unique_together=set(),
        ),
    ]
