# Generated by Django 3.2.10 on 2022-01-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_remove_cart_sales_tax'),
        ('order_checkout_app', '0003_alter_ordercheckout_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercheckout',
            unique_together={('order_id', 'cart')},
        ),
    ]
