# Generated by Django 3.2.10 on 2022-01-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_alter_billingprofile_user'),
        ('order_checkout_app', '0004_alter_ordercheckout_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordercheckout',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.billingprofile'),
        ),
    ]
