# Generated by Django 3.2.10 on 2022-02-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_checkout_app', '0005_auto_20220126_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercheckout',
            unique_together=set(),
        ),
    ]
