# Generated by Django 3.2.12 on 2022-02-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0003_auto_20220205_1951'),
        ('order_checkout_app', '0006_alter_ordercheckout_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='address_app.address'),
        ),
        migrations.AddField(
            model_name='ordercheckout',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='address_app.address'),
        ),
    ]
