# Generated by Django 3.2.12 on 2022-02-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_checkout_app', '0007_auto_20220206_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='order_ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
